name:                synacor-challenge
version:             0.1.0.0
github:              "Yvee1/synacor-challenge"
license:             BSD3
author:              "Steven van den Broek"
maintainer:          "stevenvdb@live.nl"
copyright:           "2020 Steven van den Broek"

dependencies:
- base >= 4.7 && < 5
- vector
- binary
- bytestring
- split
- transformers
- containers
- mtl
- brick
- vty
- microlens-platform

library:
  source-dirs: src

executables:
  synacor-challenge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - synacor-challenge